Switch Administrador
somosdigix/Aprecie pull request #11
Opened 2022-01-05 18:56 UTC by AleeLouffer

2022-01-13 15:19 UTC, viniciuslima-dgx requested changes

2022-01-13 15:19 UTC, viniciuslima-dgx commented on static/app/botaoReconhecer/botaoReconhecer.js
> +				console.log(ultimaData);
console.log

2022-01-13 15:19 UTC, viniciuslima-dgx commented on Reconhecimentos/views.py
> +def switch_administrador(requisicao):
Como que garantimos que alguém que não é administrador não chame isso aqui tornando alguém ou removendo o status de administrador de alguém?

2022-01-13 15:19 UTC, viniciuslima-dgx commented on static/app/botaoReconhecer/botaoReconhecer.js
> +	function obterDataDeReconhecimento() {
Como garantimos que o usuário não possa realmente reconhecer mais de uma vez no mesmo dia? Existe validação no backend? Somente no js do front não garante isso.

2022-02-01 18:47 UTC, vsaueia commented on Login/views.py
> +	  'nome_do_colaborador': colaborador_autenticado.primeiro_nome,
parece que a identação aqui e na linha de baixo ficaram erradas

2022-02-01 18:47 UTC, vsaueia commented on Reconhecimentos/views.py
> +    switch_convertido = converte_boolean(switch_administrador)
esse nome "switch_convertido" não ficou muito claro pra mim, pode ser um eh_administrador ou algo do tipo para dar mais clareza que é um boolean sobre adminstrador

2022-02-01 18:47 UTC, vsaueia commented on static/app/botaoReconhecer/botaoReconhecer.js
> +	var contagem_carac = box.length;
abreviação que não precisa, pode usar contagem_de_caracteres, use sempre as preposições e nomes sem abreviações

2022-02-02 19:59 UTC, vsaueia approved these changes

2022-02-02 20:01 UTC, viniciuslima-dgx approved these changes

2022-02-07 18:30 UTC, merged