Corrigindo Bugs da Master Atual
somosdigix/Aprecie pull request #14
Opened 2022-01-19 18:23 UTC by AleeLouffer

2022-01-24 21:11 UTC, viniciuslima-dgx requested changes

2022-01-26 19:02 UTC, renansmoreira requested changes

2022-01-26 19:02 UTC, renansmoreira commented on static/app/perfil/apreciacoesPrint.js
> +	return primeiro_nome + " " + ultimo_nome;
O backend já tem no modelo de dados o nome da pessoa e o nome "de exibição", que é uma versão mais curta. Pq isso tá replicado no front agora?

2022-01-26 19:02 UTC, renansmoreira commented on static/app/perfil/apreciar.js
> +				} else if (dataDePublicacao.ultima_data == dataHoje) {
Esse código já não tá em outro canto? Pq duplicado?

2022-01-27 19:02 UTC, renansmoreira requested changes

2022-01-27 19:02 UTC, renansmoreira commented on Reconhecimentos/views.py
> +  }, reconhecido.reconhecimentos())
Dois pontos aqui:
- Trocou 6 por meia dúzia, dava só pra ter adicionado o `'id'` na lista de `values` que já tinha antes  pra ter o mesmo resultado;
- Notei a remoção da ordenação, tá certo isso?

2022-01-27 19:02 UTC, renansmoreira commented on Reconhecimentos/views.py
> +    'apreciacoes': list(sorted(sorted(apreciacoes, key=lambda x: x["data"], reverse=True), key=lambda y: y["id"], reverse=True))
Acho que era melhor ter mantido a ordenação no de cima pra reduzir a complexidade deste cara aqui. Só não entendi o pq ordena pela data se no fim o que prevalece é a ordenação por id

2022-01-27 19:05 UTC, AleeLouffer commented on Reconhecimentos/views.py
> +  }, reconhecido.reconhecimentos())
O values não pegava o @property nome_abreviado, então esse foi o jeito que achamos de passar o nome abreviado direto para o front.

2022-02-01 18:22 UTC, renansmoreira approved these changes

2022-02-01 19:11 UTC, viniciuslima-dgx approved these changes

2022-02-01 20:08 UTC, merged