Adicionando ciclo futuro
somosdigix/Aprecie pull request #39
Opened 2022-03-15 20:58 UTC by camilavitoriacosta

2022-03-16 19:41 UTC, viniciuslima-dgx requested changes

2022-03-16 19:41 UTC, viniciuslima-dgx commented on Reconhecimentos/models.py
> +    if self.data_final != None and data_inicial >= self.data_final:
Isso me parece mais uma situação de erro que deveria lançar uma exceção do que setar como none a data final. O if está dizendo "Se a data final existir e for menor ou igual a inicial, setar a data final como None". Não entendi o motivo dessa lógica ao invés disso ser um erro.

2022-03-16 19:41 UTC, viniciuslima-dgx commented on static/app/gerenciadorDeCiclos/botaoAdicionarCicloTemplate.html
> +    <div class="falha-data-inicial-menor">⚠ Coloque um data inicial maior que a data atual!</div>
Erro no texto. Um**a** data

2022-03-16 19:41 UTC, viniciuslima-dgx commented on static/app/gerenciadorDeCiclos/cicloAtualTemplate.html
> +					<div class="falha-data-final-menor-alterada">⚠ Coloque um data final maior que a data inicial!</div>
Mesmo problema da escrita

2022-03-29 18:49 UTC, vsaueia approved these changes

2022-03-29 19:26 UTC, merged