Criando Servico de Print
somosdigix/Aprecie pull request #6
Opened 2021-12-01 20:11 UTC by AleeLouffer

Criando serviço que printa um comentário recebido.

2021-12-15 18:36 UTC, vsaueia requested changes

2021-12-15 18:36 UTC, vsaueia commented on static/app/perfil/apreciacoes.js
> +        for(var i=0; i-fulano.length; i++){
acho que fulano não é uma boa escolha de nome para a variável, use algo mais próximo do conceito final "usuário" ou algo do tipo

2021-12-15 18:36 UTC, vsaueia commented on static/app/perfil/apreciacoes.js
> +        for(var i=0; i-fulano.length; i++){
acho que fulano não é uma boa escolha de nome para a variável, use algo mais próximo do conceito final "usuário" ou algo do tipo

2021-12-15 18:36 UTC, vsaueia commented on static/app/perfil/apreciacoesPrint.js
> +  setTimeout(() => gerarModal(), 250);
porque isso aqui é necessário?

2021-12-15 18:36 UTC, vsaueia commented on static/app/perfil/apreciacoesPrint.js
> +function sumirModal() {
não é incorreto, mas sumir é um termo menos usual, recomendo "esconderModal"

2021-12-15 18:36 UTC, vsaueia commented on static/app/perfil/apreciacoesPrint.js
> +function SaveAs() {
todos os demais métodos estão em português e com letra minúscula, esse aqui fugiu do padrão. Corrigir

2021-12-15 18:36 UTC, vsaueia commented on static/app/perfil/apreciacoesTemplate.html
> +<style>
porque esses estilos estão aqui e não em um css separado?

2021-12-15 19:36 UTC, camilavitoriacosta commented on static/app/perfil/apreciacoesPrint.js
> +  setTimeout(() => gerarModal(), 250);
é necessário para que o card seja gerado com todos os elementos ao mesmo tempo, é apenas uma melhoria visual.

2021-12-15 19:46 UTC, camilavitoriacosta commented on static/app/perfil/apreciacoesTemplate.html
> +<style>
não estamos conseguindo colocar em um arquivo css separado, mesmo referenciando.

2021-12-21 13:29 UTC, vsaueia commented on static/app/perfil/apreciacoes.js
> +        for(var i=0; i-usuario.length; i++){
não entendi essa condição i-usuario.length, não era pra ser i < usuario.length?

2021-12-21 13:29 UTC, vsaueia commented on static/app/perfil/apreciacoesPrint.js
> +  setTimeout(() => gerarModal(), 250);
Não convence muito não, ficar distribuindo esses timeouts não costuma ser uma boa prática, qual o prejuízo se tirado?

2022-01-03 15:14 UTC, vsaueia approved these changes

2022-01-03 15:14 UTC, merged