Colaborador fazer uma apreciacao por dia
somosdigix/Aprecie pull request #8
Opened 2021-12-15 21:14 UTC by AleeLouffer

2021-12-21 13:35 UTC, vsaueia commented on static/app/perfil/apreciar.js
> +		if (sessaoDeUsuario.id === colaboradorId) return;
o padrão é na linha de baixo mesmo, como estava

2022-01-03 15:42 UTC, vsaueia requested changes

2022-01-03 15:42 UTC, vsaueia commented on static/app/perfil/apreciar.js
> +		var dd = String(hoje.getDate()).padStart(2, "0");
use o significado da variável no nome dd = dia

2022-01-03 15:42 UTC, vsaueia commented on static/app/perfil/apreciar.js
> +		var mm = String(hoje.getMonth() + 1).padStart(2, "0");
mm = mes

2022-01-03 15:42 UTC, vsaueia commented on static/app/perfil/apreciar.js
> +		var yyyy = hoje.getFullYear();
yyyy = ano

2022-01-03 15:42 UTC, vsaueia commented on static/app/perfil/apreciar.js
> +		var hoje = new Date();
Não tem uma forma de passar o formato por aqui já? evitando as partes que seguem aí abaixo

2022-01-03 15:42 UTC, vsaueia commented on static/app/perfil/apreciar.js
> +				"O descritivo da sua apreciação precisa ser informado"
Acho que fica melhor "A apreciação precisa ser feita"

2022-01-05 14:55 UTC, vsaueia commented on static/app/perfil/apreciar.js
> +							"Nao pode ser feito mais de um reconhecimento no mesmo dia"
não é mais legal colocar no positivo: "você já fez sua apreciação de hoje, amanhã você poderá fazer outra"?

2022-01-05 14:55 UTC, vsaueia commented on static/app/perfil/apreciar.js
> +			growl.deSucesso().exibir("Reconhecimento realizado com sucesso.");
Devemos manter uma linguagem única, ou usamos reconhecimento ou apreciação. Ficar mudando termos não é necessariamente bom para o usuário

2022-01-10 17:36 UTC, viniciuslima-dgx requested changes

2022-01-10 17:36 UTC, viniciuslima-dgx commented on static/app/perfil/apreciar.js
> +				"A apreciação precisa ser feita."
Não cai no mesmo ponto do comentário que o Vini tinha feito quanto a ter dois termos pra uma mesma coisa? Na parte que vcs corrigiram ficou "Reconhecimento" e aqui nessa regra está "Apreciação"

2022-01-10 17:36 UTC, viniciuslima-dgx commented on Login/models.py
> +	ultima_apreciacao = models.DateField(null=True)
Não seria melhor indicar no nome que esta propriedade é a data de última apreciação? Sem isso pode gerar confusão quanto a ser a última apreciação ou não, olhando no banco. Precisando o dev olhar para o tipo da coluna pra entender.

2022-01-10 17:36 UTC, viniciuslima-dgx commented on Login/models.py
> +	ultima_apreciacao = models.DateField(null=True)
Aqui a nomenclatura vai ficar apreciação ou reconhecimento?

2022-01-10 18:31 UTC, viniciuslima-dgx requested changes

2022-01-10 18:31 UTC, viniciuslima-dgx commented on Login/migrations/0003_colaborador_ultima_apreciacao.py
> +
Depois da alteração da model, a migration ficou errada

2022-01-11 17:24 UTC, merged