Ranking 10 primeiros
somosdigix/Aprecie pull request #9
Opened 2021-12-23 20:11 UTC by AleeLouffer

2022-01-05 14:57 UTC, vsaueia reviewed
Essa PR deve ter ficado desatualizada ou são 48 arquivos mesmo?

2022-01-11 17:48 UTC, viniciuslima-dgx requested changes

2022-01-11 17:48 UTC, viniciuslima-dgx commented on .vs/VSWorkspaceState.json
> +    "",
todos esses arquivos da pasta .vs não devem ser comitados. Sugiro incluir no gitignore.

2022-01-11 17:48 UTC, viniciuslima-dgx commented on static/app/ranking/ranking.js
> +		img.id = "posicao";
Como o identificador de uma img deve ser único por página, sugiro alterar isso aqui para conter pelo menos o número "i" junto.

2022-01-11 17:48 UTC, viniciuslima-dgx commented on Login/migrations/0004_remove_colaborador_quantidade_de_apreciacoes_recebidas.py
> +    operations = [
Por qual motivo foi criada uma Migration pra adicionar um campo e logo em seguida uma pra remover?

2022-01-11 17:48 UTC, viniciuslima-dgx commented on Login/models.py
> +		self.incrementar_quantidade_reconhecimentos()
não encontrei esse método

2022-01-11 18:04 UTC, AleeLouffer commented on Login/migrations/0004_remove_colaborador_quantidade_de_apreciacoes_recebidas.py
> +    operations = [
Iriamos criar um método para contar a quantidade de reconhecimentos, mas no meio do caminho descobrimos que o sistema já fazia o que precisávamos.

2022-01-11 18:10 UTC, viniciuslima-dgx approved these changes

2022-01-11 18:15 UTC, merged